// script.js - Simple Todo App
// Author: Generated by CODER AGENT

(() => {
  // ---------- Todo Class ----------
  class Todo {
    /**
     * @param {number} id
     * @param {string} text
     * @param {boolean} completed
     */
    constructor(id, text, completed = false) {
      this.id = id;
      this.text = text;
      this.completed = completed;
    }
  }

  // ---------- Storage Module ----------
  const Storage = (() => {
    const STORAGE_KEY = 'simpleTodoApp';

    /** Load todos from localStorage */
    function loadTodos() {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return [];
      try {
        const parsed = JSON.parse(raw);
        // Ensure objects are instances of Todo
        return parsed.map(item => new Todo(item.id, item.text, item.completed));
      } catch (e) {
        console.error('Failed to parse todos from storage', e);
        return [];
      }
    }

    /** Save todos array to localStorage */
    function saveTodos(todos) {
      try {
        const data = JSON.stringify(todos);
        localStorage.setItem(STORAGE_KEY, data);
      } catch (e) {
        console.error('Failed to save todos to storage', e);
      }
    }

    return { loadTodos, saveTodos };
  })();

  // ---------- UI Module ----------
  const UI = (() => {
    // Cache DOM elements
    const newTodoInput = document.getElementById('new-todo');
    const addBtn = document.getElementById('add-btn');
    const todoList = document.getElementById('todo-list');
    const filterBtns = document.querySelectorAll('.filter-btn');
    const clearCompletedBtn = document.getElementById('clear-completed');

    /** Render the todo list based on current filter */
    function renderTodos(todos, filter) {
      // Clear existing list
      todoList.innerHTML = '';

      const filtered = todos.filter(todo => {
        if (filter === 'active') return !todo.completed;
        if (filter === 'completed') return todo.completed;
        return true; // 'all'
      });

      filtered.forEach(todo => {
        const li = document.createElement('li');
        li.className = 'todo-item';
        if (todo.completed) li.classList.add('completed');
        li.dataset.id = todo.id; // store id for later reference

        // Checkbox
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.checked = todo.completed;
        checkbox.className = 'todo-checkbox';
        li.appendChild(checkbox);

        // Text span
        const span = document.createElement('span');
        span.textContent = todo.text;
        span.className = 'todo-text';
        li.appendChild(span);

        // Delete button
        const delBtn = document.createElement('button');
        delBtn.textContent = 'Delete';
        delBtn.className = 'delete-btn';
        li.appendChild(delBtn);

        todoList.appendChild(li);
      });
    }

    /** Get the currently active filter string */
    function getCurrentFilter() {
      const activeBtn = document.querySelector('.filter-btn.active');
      return activeBtn ? activeBtn.dataset.filter : 'all';
    }

    /** Attach all required event listeners */
    function bindEvents(appState) {
      // Add new todo via button click
      addBtn.addEventListener('click', () => {
        const text = newTodoInput.value.trim();
        if (!text) return;
        appState.addTodo(text);
        newTodoInput.value = '';
      });

      // Add new todo via Enter key
      newTodoInput.addEventListener('keypress', e => {
        if (e.key === 'Enter') {
          const text = newTodoInput.value.trim();
          if (!text) return;
          appState.addTodo(text);
          newTodoInput.value = '';
        }
      });

      // Delegate checkbox change and delete button click within the list
      todoList.addEventListener('change', e => {
        if (e.target && e.target.matches('input.todo-checkbox')) {
          const li = e.target.closest('li.todo-item');
          const id = Number(li.dataset.id);
          appState.toggleTodo(id, e.target.checked);
        }
      });

      todoList.addEventListener('click', e => {
        if (e.target && e.target.matches('button.delete-btn')) {
          const li = e.target.closest('li.todo-item');
          const id = Number(li.dataset.id);
          appState.deleteTodo(id);
        }
      });

      // Filter buttons
      filterBtns.forEach(btn => {
        btn.addEventListener('click', () => {
          // Remove active class from all, add to clicked
          filterBtns.forEach(b => b.classList.remove('active'));
          btn.classList.add('active');
          const filter = btn.dataset.filter;
          UI.renderTodos(appState.todos, filter);
        });
      });

      // Clear completed
      clearCompletedBtn.addEventListener('click', () => {
        appState.clearCompleted();
      });
    }

    return { renderTodos, bindEvents, getCurrentFilter };
  })();

  // ---------- Main Application ----------
  const app = (() => {
    let todos = [];
    let currentFilter = 'all';

    function init() {
      todos = Storage.loadTodos();
      currentFilter = UI.getCurrentFilter();
      UI.renderTodos(todos, currentFilter);
      UI.bindEvents({
        addTodo,
        toggleTodo,
        deleteTodo,
        clearCompleted,
        get todos() { return todos; },
      });
    }

    function addTodo(text) {
      const id = Date.now(); // simple unique id based on timestamp
      const newTodo = new Todo(id, text, false);
      todos.push(newTodo);
      persistAndRender();
    }

    function toggleTodo(id, completed) {
      const todo = todos.find(t => t.id === id);
      if (todo) {
        todo.completed = completed;
        persistAndRender();
      }
    }

    function deleteTodo(id) {
      todos = todos.filter(t => t.id !== id);
      persistAndRender();
    }

    function clearCompleted() {
      todos = todos.filter(t => !t.completed);
      persistAndRender();
    }

    function persistAndRender() {
      Storage.saveTodos(todos);
      UI.renderTodos(todos, UI.getCurrentFilter());
    }

    return { init };
  })();

  // Expose globally
  window.todoApp = { init: app.init };
  // Auto‑initialize the app
  document.addEventListener('DOMContentLoaded', () => {
    app.init();
  });
})();
